---
apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  annotations:
    notebooks.opendatahub.io/inject-auth: "true"
    notebooks.opendatahub.io/last-image-selection: training-hub-universal-cpu:3.4
    notebooks.opendatahub.io/last-image-version-git-commit-selection: a66ec72
    opendatahub.io/connections: ""
    opendatahub.io/hardware-profile-name: workshop-profile
    opendatahub.io/hardware-profile-namespace: redhat-ods-applications
    opendatahub.io/image-display-name: Training | Jupyter | PyTorch | CPU | Python
    opendatahub.io/mlflow-instance: mlflow
    opendatahub.io/user: user0
    opendatahub.io/username: user0
    opendatahub.io/workbench-image-namespace: ""
    openshift.io/description: RAG on prem
    openshift.io/display-name: workbench
  labels:
    app: workbench
    opendatahub.io/dashboard: "true"
    opendatahub.io/odh-managed: "true"
  name: workbench
spec:
  template:
    spec:
      containers:
      - env:
        - name: NOTEBOOK_ARGS
          value: |-
            --ServerApp.port=8888
                              --ServerApp.token=''
                              --ServerApp.password=''
                              --ServerApp.base_url=/notebook/user0/workbench
                              --ServerApp.quit_button=False
        - name: JUPYTER_IMAGE
          value: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/training-hub-universal-cpu:3.4
        - name: PIP_CERT
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: REQUESTS_CA_BUNDLE
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: SSL_CERT_FILE
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: PIPELINES_SSL_SA_CERTS
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: KF_PIPELINES_SSL_SA_CERTS
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: GIT_SSL_CAINFO
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: MLFLOW_K8S_INTEGRATION
          value: "true"
        - name: MLFLOW_TRACKING_AUTH
          value: kubernetes-namespaced
        image: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/training-hub-universal-cpu:3.4
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /notebook/user0/workbench/api
            port: notebook-port
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: workbench
        ports:
        - containerPort: 8888
          name: notebook-port
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /notebook/user0/workbench/api
            port: notebook-port
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: "2"
            memory: 4Gi
        volumeMounts:
        - mountPath: /opt/app-root/src/
          name: workbench-storage
        - mountPath: /dev/shm
          name: shm
        - mountPath: /etc/pki/tls/custom-certs
          name: trusted-ca
          readOnly: true
        - mountPath: /opt/app-root/pipeline-runtimes/
          name: runtime-images
        workingDir: /opt/app-root/src
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8888/
        - --logtostderr=true
        - --v=10
        - --proxy-endpoints-port=8444
        - --config-file=/etc/kube-rbac-proxy/config-file.yaml
        - --tls-cert-file=/etc/tls/private/tls.crt
        - --tls-private-key-file=/etc/tls/private/tls.key
        - --auth-header-fields-enabled=true
        - --auth-header-user-field-name=X-Auth-Request-User
        - --auth-header-groups-field-name=X-Auth-Request-Groups
        image: registry.redhat.io/rhoai/odh-kube-auth-proxy-rhel9@sha256:a059f453011028f7f18b3c7ec6406a958aa7a5b9bf6c67d084ea9d5d36d6c970
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8444
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: kube-rbac-proxy
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8444
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
        volumeMounts:
        - mountPath: /etc/kube-rbac-proxy
          name: kube-rbac-proxy-config
        - mountPath: /etc/tls/private
          name: kube-rbac-proxy-tls-certificates
      enableServiceLinks: false
      volumes:
      - name: workbench-storage
        persistentVolumeClaim:
          claimName: workbench-storage
      - emptyDir:
          medium: Memory
        name: shm
      - configMap:
          name: workbench-trusted-ca-bundle
          optional: true
        name: trusted-ca
      - configMap:
          name: pipeline-runtime-images
          optional: true
        name: runtime-images
      - configMap:
          defaultMode: 420
          name: workbench-kube-rbac-proxy-config
        name: kube-rbac-proxy-config
      - name: kube-rbac-proxy-tls-certificates
        secret:
          defaultMode: 420
          secretName: workbench-kube-rbac-proxy-tls
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    openshift.io/display-name: workbench-storage
  labels:
    opendatahub.io/dashboard: "true"
  name: workbench-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
