apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: github-workshop
spec:
  href: https://github.com/adrezni/rag-onprem
  location: ApplicationMenu
  text: GitHub - RAG On Prem
  applicationMenu:
    section: Git Repos
    imageURL: /static/assets/public/imgs/logos/github.svg
